---
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
name: Check code style

jobs:
  check-code-style:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
    # 1. Format the code
    # 2. If code was formatted, fail and open up a PR to fix it
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Black Code Formatter
      uses: lgeiger/black-action@master
      with:
        args: .
    - name: Check if code formatters applied changes
      uses: tj-actions/verify-changed-files@v16
      id: verify-changed-files
      with:
        files: |
          **/*.py
    - name: Create Pull Request if code formatters fixed something
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Code formatting tool on ${{ github.head_ref }}
        title: Code formatting for ${{ github.head_ref }}
        body: Auto-generated PR with fixes by code formatting tools
        labels: code formatters, automated pr
        branch: formatter-patches/${{ github.head_ref }}
    - name: Fail flow if code formatters found issues
      if: steps.verify-changed-files.outputs.files_changed == 'true'
      run: exit 1
